import { Inter, Zain } from "next/font/google";
import "./globals.css";
// LIBRARIES
import { useTranslation } from "../i18n";
import { languages } from "../i18n/settings";
import { dir } from "i18next";

const inter = Inter({ subsets: ["latin"] });
const zain = Zain({
  subsets: ["arabic"],
  weight: [ "700", "800", "900"],
});


export function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: "ATHAN",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lng } }) {
  const { t } = await useTranslation(lng);
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={lng === "en" ? inter.className : zain.className}>
        {children}
      </body>
    </html>
  );
}
